import type { Camera, PayloadPreset } from "./types";

export const SWAPPABLE_PAYLOADS: Record<string, PayloadPreset> = {
  H20: { name: "H20", payloadEnum: 42, payloadSubEnum: 0, orientedCameraType: 52 },
  H20T: { name: "H20T", payloadEnum: 43, payloadSubEnum: 0, orientedCameraType: 53 },
  H20N: { name: "H20N", payloadEnum: 61, payloadSubEnum: 0 },
  H30: { name: "H30", payloadEnum: 82, payloadSubEnum: 0 },
  H30T: { name: "H30T", payloadEnum: 83, payloadSubEnum: 0 },
  "PSDK Device": { name: "PSDK Device", payloadEnum: 65534, payloadSubEnum: 0 },
};

export const CAMERAS: Record<string, Camera> = {
  "M300 RTK": {
    name: "M300 RTK",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 60,
    droneSubEnum: 0,
    payloadEnum: null,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 52,
    payloadPositionIndex: 0,
    supportsPayloadSwap: true,
    isLidar: false,
    isRtk: true,
  },
  M30: {
    name: "M30",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 67,
    droneSubEnum: 0,
    payloadEnum: 52,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 52,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: false,
  },
  M30T: {
    name: "M30T",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 67,
    droneSubEnum: 1,
    payloadEnum: 53,
    payloadSubEnum: 0,
    imageFormat: "visible,ir",
    orientedCameraType: 53,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: false,
  },
  M3E: {
    name: "M3E",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 77,
    droneSubEnum: 0,
    payloadEnum: 66,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 66,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: true,
  },
  M3T: {
    name: "M3T",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 77,
    droneSubEnum: 1,
    payloadEnum: 67,
    payloadSubEnum: 0,
    imageFormat: "visible,ir",
    orientedCameraType: 66,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: true,
  },
  M3M: {
    name: "M3M",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 77,
    droneSubEnum: 2,
    payloadEnum: 68,
    payloadSubEnum: 0,
    imageFormat: "visible,narrow_band",
    orientedCameraType: 66,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: true,
    isRtk: true,
  },
  "M350 RTK": {
    name: "M350 RTK",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 89,
    droneSubEnum: 0,
    payloadEnum: null,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 52,
    payloadPositionIndex: 0,
    supportsPayloadSwap: true,
    isLidar: false,
    isRtk: true,
  },
  M3D: {
    name: "M3D",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 91,
    droneSubEnum: 0,
    payloadEnum: 80,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 80,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: true,
  },
  M3TD: {
    name: "M3TD",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 91,
    droneSubEnum: 1,
    payloadEnum: 81,
    payloadSubEnum: 0,
    imageFormat: "visible,ir",
    orientedCameraType: 80,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: true,
  },
  "M4D Wide (24mm)": {
    name: "M4D Wide (24mm)",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 100,
    droneSubEnum: 0,
    payloadEnum: 98,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 99,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: false,
  },
  "M4E Wide (24mm)": {
    name: "M4E Wide (24mm)",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 100,
    droneSubEnum: 0,
    payloadEnum: 98,
    payloadSubEnum: 0,
    imageFormat: "visible",
    orientedCameraType: 99,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: false,
  },
  "M4T (Thermal)": {
    name: "M4T (Thermal)",
    sensorWidthMm: 9.6,
    sensorHeightMm: 7.2,
    focalLengthMm: 6.72,
    imageWidthPx: 5280,
    imageHeightPx: 3956,
    droneEnum: 100,
    droneSubEnum: 1,
    payloadEnum: 99,
    payloadSubEnum: 2,
    imageFormat: "visible,ir",
    orientedCameraType: 99,
    payloadPositionIndex: 0,
    supportsPayloadSwap: false,
    isLidar: false,
    isRtk: false,
  },
};

export const DEFAULT_CAMERA_KEY = "M4D Wide (24mm)";

export function getPayloadOptions(camera: Camera): PayloadPreset[] {
  if (!camera.supportsPayloadSwap) return [];
  return Object.values(SWAPPABLE_PAYLOADS);
}

export function resolveCameraPayload(camera: Camera, payloadKey?: string): Camera {
  if (!camera.supportsPayloadSwap) return camera;
  const payload = payloadKey ? SWAPPABLE_PAYLOADS[payloadKey] : SWAPPABLE_PAYLOADS.H20;
  return {
    ...camera,
    payloadEnum: payload.payloadEnum,
    payloadSubEnum: payload.payloadSubEnum,
    orientedCameraType: payload.orientedCameraType ?? camera.orientedCameraType,
    isLidar: payload.isLidar ?? camera.isLidar,
  };
}

